import React from 'react';
import { ArrowRight, X } from 'lucide-react';
import type { CaseRecord } from '../../types/crime';

interface Props { title: string; records: CaseRecord[]; onClose: () => void; onOpenCase: (record: CaseRecord) => void; }
export const EvidenceDrilldown: React.FC<Props> = ({ title, records, onClose, onOpenCase }) => {
  const active = records.filter(record => record.status !== 'CLOSED');
  const oldest = records.reduce((max, record) => Math.max(max, Number(record.daysAging || 0)), 0);
  const leadStatus = active.length ? 'UNDER INVESTIGATION' : 'CLOSED';
  return <div className="evidence-overlay" onMouseDown={onClose}><section className="evidence-sheet" role="dialog" aria-modal="true" aria-label={`${title} evidence`} onMouseDown={event => event.stopPropagation()}>
    <header><div><span className={`evidence-status ${active.length ? 'active' : 'closed'}`}>{leadStatus}</span><h2>{title}</h2><p>{records.length} verified FIR records</p></div><button className="btn btn-icon" onClick={onClose} aria-label="Close evidence"><X size={20}/></button></header>
    <div className="evidence-summary"><strong>Case summary:</strong> {active.length} active records; oldest case age is {oldest} days.</div>
    <h3>Cases in this selection ({records.length})</h3>
    <div className="evidence-cases">{records.map(record => <article key={record.id}><div className="evidence-case-top"><code>{record.firNumber}</code><span className={`evidence-status ${record.status === 'CLOSED' ? 'closed' : 'active'}`}>{record.status.replaceAll('_',' ')}</span></div><h4>{record.title}</h4><p>{record.location.district} · {record.daysAging} days open</p><div className="evidence-method"><strong>Crime method:</strong> {record.modusOperandi?.primaryMethod || 'Not classified'}</div><footer><span>Accused: {record.accused.map(item => item.name).join(', ') || 'No linked accused'}</span><button className="btn btn-primary" onClick={() => { onClose(); onOpenCase(record); }}>View full case <ArrowRight size={16}/></button></footer></article>)}</div>
    {!records.length&&<div className="evidence-empty">No FIR records match this selection.</div>}
  </section><style>{`.evidence-overlay{position:fixed;inset:0;z-index:600;background:rgba(4,14,29,.72);display:grid;place-items:center;padding:1rem}.evidence-sheet{width:min(940px,100%);max-height:92vh;overflow-y:auto;background:var(--surface-elevated);color:var(--text-primary);border:1px solid var(--border);border-radius:var(--radius-lg);box-shadow:var(--shadow-lg);padding:1rem}.evidence-sheet>header{display:flex;justify-content:space-between;gap:1rem;padding-bottom:1rem;border-bottom:1px solid var(--border)}.evidence-sheet h2{font-size:1.35rem;margin:.55rem 0 .15rem}.evidence-sheet header p{margin:0;color:var(--critical);font-weight:750}.evidence-status{display:inline-flex;width:max-content;padding:.3rem .55rem;border-radius:var(--radius-sm);font-size:.68rem;font-weight:850;text-transform:uppercase}.evidence-status.active{background:color-mix(in srgb,var(--warning) 18%,transparent);border:1px solid var(--warning);color:var(--warning)}.evidence-status.closed{background:color-mix(in srgb,var(--info) 16%,transparent);border:1px solid var(--info);color:var(--info)}.evidence-summary{margin:1.2rem 0;padding:1rem;border:1px solid var(--border);background:var(--surface-card);border-radius:var(--radius-md)}.evidence-sheet>h3{font-size:.95rem}.evidence-cases{display:grid;gap:.75rem}.evidence-cases article{padding:1rem;border:1px solid var(--border);background:var(--surface-card);border-radius:var(--radius-md)}.evidence-case-top,.evidence-cases footer{display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap}.evidence-case-top code{color:var(--accent);font-weight:800}.evidence-cases h4{font-size:1rem;margin:.7rem 0 .35rem}.evidence-cases p,.evidence-cases footer span{color:var(--text-secondary);font-size:.8rem}.evidence-method{margin:.7rem 0;padding:.7rem;background:var(--surface-muted);border-radius:var(--radius-sm);font-size:.8rem}.evidence-cases footer{margin-top:.8rem}.evidence-empty{padding:2rem;text-align:center;color:var(--text-muted)}@media(max-width:640px){.evidence-overlay{padding:0}.evidence-sheet{height:100%;max-height:none;border-radius:0}.evidence-cases footer{align-items:stretch}.evidence-cases footer .btn{width:100%}}`}</style>
  </div>;
};
